#!/bin/bash
#   DEPLOYMENT SCRIPT FOR TF MODULE
TOMCAT_URI=https://www-eu.apache.org/dist/tomcat/tomcat-9/v9.0.17/bin/apache-tomcat-9.0.17.tar.gz

function installTomcat(){
 sudo yum update -y && sudo yum install -y nano net-tools wget java
 sudo useradd -m -U -d /opt/tomcat -s /bin/false tomcat
 cd /tmp
 sudo wget ${TOMCAT_URI}
 sudo tar -xf apache-tomcat-*
 sudo mv apache-tomcat-9.0.17 /opt/tomcat/
 sudo ln -s /opt/tomcat/apache-tomcat-9.0.17 /opt/tomcat/latest
 sudo chown -R tomcat: /opt/tomcat
 sudo sh -c 'chmod +x /opt/tomcat/latest/bin/*.sh'
 sudo touch /etc/systemd/system/tomcat.service &&
 sudo echo "[Unit]
Description=Tomcat 9 servlet container
After=network.target

[Service]
Type=forking

User=tomcat
Group=tomcat

Environment="JAVA_HOME=/usr/lib/jvm/jre"
Environment="JAVA_OPTS=-Djava.security.egd=file:///dev/urandom"

Environment="CATALINA_BASE=/opt/tomcat/latest"
Environment="CATALINA_HOME=/opt/tomcat/latest"
Environment="CATALINA_PID=/opt/tomcat/latest/temp/tomcat.pid"
Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"

ExecStart=/opt/tomcat/latest/bin/startup.sh
ExecStop=/opt/tomcat/latest/bin/shutdown.sh

[Install]
WantedBy=multi-user.target" >> /etc/systemd/system/tomcat.service &&

 sudo systemctl daemon-reload
 sudo systemctl enable tomcat
 sudo systemctl start tomcat
 sudo systemctl status tomcat

}
 
function main(){
  installTomcat
}
main
